[mgr]
ratio = [ 1, 2, 3 ]

[preview]
max_width  = 1920
max_height = 1080

[opener]
open = [ { run = "nuke %s", desc = "Open", for = "linux" }, ]
play = [ { run = "nuke %s", desc = "Play", for = "linux" }, ]
